import { ArrowUpRight, Github } from "lucide-react"

const projects = [
  { title: "OT-Microservices CI/CD", description: "A production-oriented delivery workflow for automated build, test and deployment of a Java microservices project.", tags: ["Jenkins", "GitHub Actions", "Azure DevOps", "Maven"], logos: [["https://cdn.simpleicons.org/jenkins","Jenkins"],["https://cdn.simpleicons.org/githubactions","GitHub Actions"],["https://cdn.simpleicons.org/azuredevops","Azure DevOps"]], url: "https://github.com/himanshu085/ot-microservices", label: "CI/CD" },
  { title: "Dynamic Kafka Infrastructure", description: "Terraform-based infrastructure code for repeatable Kafka cluster provisioning and cloud infrastructure automation.", tags: ["Terraform", "AWS", "Azure", "Kafka"], logos: [["https://cdn.simpleicons.org/terraform","Terraform"],["https://cdn.simpleicons.org/amazonaws","AWS"],["https://cdn.simpleicons.org/microsoftazure","Azure"],["https://cdn.simpleicons.org/apachekafka","Kafka"]], url: "https://github.com/himanshu085/kafka_dynamic", label: "Cloud + IaC" },
  { title: "Dynamic Kafka Ansible Roles", description: "Reusable Ansible roles for dynamic Kafka deployment and configuration, designed around scalable automation.", tags: ["Ansible", "Kafka", "Linux", "Automation"], logos: [["https://cdn.simpleicons.org/ansible","Ansible"],["https://cdn.simpleicons.org/apachekafka","Kafka"],["https://cdn.simpleicons.org/linux","Linux"]], url: "https://github.com/himanshu085/roles_kafka_dynamic", label: "Automation" },
  { title: "Jenkins Shared Library", description: "Reusable CI/CD functions and utilities that standardize pipeline patterns across multiple projects.", tags: ["Jenkins", "GitHub Actions", "Groovy", "CI/CD"], logos: [["https://cdn.simpleicons.org/jenkins","Jenkins"],["https://cdn.simpleicons.org/githubactions","GitHub Actions"],["https://cdn.simpleicons.org/groovy","Groovy"]], url: "https://github.com/himanshu085/shared-Library", label: "Platform Engineering" },
]

export function Projects() {
  return <section id="projects" className="border-y border-white/5 bg-white/[0.015] py-24"><div className="section-shell"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-mono text-xs uppercase tracking-[0.25em] text-cyan-400">04 / PROJECTS</p><h2 className="mt-4 text-3xl font-bold text-white sm:text-4xl">Selected engineering work.</h2></div><a href="https://github.com/himanshu085" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-cyan-300">View GitHub <ArrowUpRight size={16}/></a></div><div className="mt-10 grid gap-5 md:grid-cols-2">{projects.map(project => <div key={project.title} className="group overflow-hidden rounded-2xl border border-white/10 bg-[#0b1018] transition hover:-translate-y-1 hover:border-cyan-400/25"><div className="relative flex aspect-[16/8] items-center justify-center overflow-hidden border-b border-white/10 bg-[radial-gradient(circle_at_50%_40%,rgba(34,211,238,.14),transparent_55%),linear-gradient(135deg,#111827,#080b11)]"><div className="absolute inset-0 opacity-30" style={{backgroundImage:"linear-gradient(rgba(148,163,184,.08) 1px,transparent 1px),linear-gradient(90deg,rgba(148,163,184,.08) 1px,transparent 1px)",backgroundSize:"32px 32px"}} /><div className="relative flex flex-wrap items-center justify-center gap-3 px-8">{project.logos.map(([src,name]) => <div key={name} className="flex h-16 w-16 items-center justify-center rounded-2xl border border-white/10 bg-white/[0.06] p-4 shadow-2xl backdrop-blur transition duration-500 group-hover:border-cyan-400/20 group-hover:bg-white/[0.09]"><img src={src} alt={name} className="h-full w-full object-contain" /></div>)}</div><span className="absolute left-5 top-5 rounded-full border border-cyan-400/20 bg-[#070a0f]/75 px-3 py-1 font-mono text-[10px] uppercase tracking-[0.16em] text-cyan-300 backdrop-blur">{project.label}</span></div><div className="p-6"><div className="flex items-start justify-between gap-4"><h3 className="text-xl font-semibold text-white">{project.title}</h3><a href={project.url} target="_blank" rel="noreferrer" aria-label={"Open " + project.title + " on GitHub"} className="rounded-lg border border-white/10 p-2 text-slate-400 hover:border-cyan-400/30 hover:text-cyan-300"><Github size={17}/></a></div><p className="mt-3 leading-7 text-slate-500">{project.description}</p><div className="mt-5 flex flex-wrap gap-2">{project.tags.map(tag => <span key={tag} className="rounded-full border border-cyan-400/10 bg-cyan-400/5 px-3 py-1 text-xs text-cyan-300">{tag}</span>)}</div></div></div>)}</div></div></section>
}
