import { ArrowUpRight, Github } from "lucide-react"

const projects = [
  { title: "OT-Microservices CI/CD", description: "A production-oriented delivery workflow for automated build, test and deployment of a Java microservices project.", image: "/images/jenkins-cicd.png", tags: ["Jenkins", "Maven", "Git", "CI/CD"], url: "https://github.com/himanshu085/ot-microservices" },
  { title: "Dynamic Kafka Infrastructure", description: "Terraform-based infrastructure code for repeatable Kafka cluster provisioning and cloud infrastructure automation.", image: "/images/kafka-logo.png", tags: ["Terraform", "Kafka", "IaC", "Cloud"], url: "https://github.com/himanshu085/kafka_dynamic" },
  { title: "Dynamic Kafka Ansible Roles", description: "Reusable Ansible roles for dynamic Kafka deployment and configuration, designed around scalable automation.", image: "/images/ansible-roles.png", tags: ["Ansible", "Kafka", "Automation"], url: "https://github.com/himanshu085/roles_kafka_dynamic" },
  { title: "Jenkins Shared Library", description: "Reusable CI/CD functions and utilities that standardize pipeline patterns across multiple projects.", image: "/images/jenkins-cicd.png", tags: ["Jenkins", "Groovy", "Shared Library"], url: "https://github.com/himanshu085/shared-Library" },
]

export function Projects() {
  return <section id="projects" className="border-y border-white/5 bg-white/[0.015] py-24"><div className="section-shell"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-mono text-xs uppercase tracking-[0.25em] text-cyan-400">04 / PROJECTS</p><h2 className="mt-4 text-3xl font-bold text-white sm:text-4xl">Selected engineering work.</h2></div><a href="https://github.com/himanshu085" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-cyan-300">View GitHub <ArrowUpRight size={16}/></a></div><div className="mt-10 grid gap-5 md:grid-cols-2">{projects.map(project => <div key={project.title} className="group overflow-hidden rounded-2xl border border-white/10 bg-[#0b1018] transition hover:-translate-y-1 hover:border-cyan-400/25"><div className="aspect-[16/8] overflow-hidden border-b border-white/10 bg-slate-900"><img src={project.image} alt="" className="h-full w-full object-cover opacity-80 transition duration-500 group-hover:scale-105 group-hover:opacity-100"/></div><div className="p-6"><div className="flex items-start justify-between gap-4"><h3 className="text-xl font-semibold text-white">{project.title}</h3><a href={project.url} target="_blank" rel="noreferrer" aria-label="Open project on GitHub" className="rounded-lg border border-white/10 p-2 text-slate-400 hover:border-cyan-400/30 hover:text-cyan-300"><Github size={17}/></a></div><p className="mt-3 leading-7 text-slate-500">{project.description}</p><div className="mt-5 flex flex-wrap gap-2">{project.tags.map(tag => <span key={tag} className="rounded-full border border-cyan-400/10 bg-cyan-400/5 px-3 py-1 text-xs text-cyan-300">{tag}</span>)}</div></div></div>)}</div></div></section>
}
